### ISSUE TITLE
Can't convert INT to currency

### ISSUE THREAD

**Issue by sebastianruehmann** [waiterio/api#5]
Convert database field type for price to float

**Comment by snapsnapturtle** [comment]
I'd rather not set the database field to a float value, as it can be quite dangerous to round those numbers as they aren't always what they seem. Here is a little code that should basically get the cents to the German currency format:

``` javascript
function convertToCurrency(centValue) {
    var number = centValue / 100;
    return number.toFixed(2).replace(/(\d)(?=(\d{3})+\,)/g, '$1.');
}
```

Here are some reasons why saving them as `float` is not an option: https://spin.atomicobject.com/2014/08/14/currency-rounding-errors/

**Comment by sebastianruehmann** [comment]
Okay, then I seek for a simple client side solution.
